---
title: "Descriptives"
execute:
  echo: false
  message: false
format: docx
toc: true
---

```{r}
#| message: false

library(groundhog)

groundhog_day <- "2024-03-01"

groundhog::meta.groundhog(groundhog_day)

groundhog::groundhog.library(
  "
library(here)
library(tidyverse)
library(scales)
library(gtsummary)
library(flextable)
library(rempsyc)
  ", date = groundhog_day
)


tab_n <- readRDS(
  here::here("02_analysis-codes", "outputs", "table_n.rds")
)

tab_uni <- readRDS(
  here::here("02_analysis-codes", "outputs", "table_uni.rds")
)

tab_cat <- readRDS(
  here::here("02_analysis-codes", "outputs", "table_cat.rds")
)


tab_list <- readRDS(
  here::here("02_analysis-codes", "outputs", "tables_uni_cat.rds")
)

plot_list <- readRDS(
  here::here("02_analysis-codes", "outputs", "plots_total.rds")
)
```

# Tables
## Number of posts by university and category
```{r}
rempsyc::nice_table(tab_n, separate.header = TRUE, italics = seq(tab_n))
```


## All posts, by university
```{r}
rempsyc::nice_table(tab_uni, separate.header = TRUE, italics = seq(tab_uni))
```

## All posts, by category
```{r}
rempsyc::nice_table(tab_cat, separate.header = TRUE, italics = seq(tab_cat))
```

## One table per category, by university

```{r}
#| output: asis

for (i in 1:length(tab_list)){
  tab <- tab_list[[i]]
  
  cat <- names(tab_list)[[i]]
  
  title <- paste0("Descriptives for ", cat, " posts, by University")
  
    cat(sep = "\n", knitr::knit_child(quiet = TRUE, text = c(
    "```{r}",
    "#| echo: false",
    "rempsyc::nice_table(tab, separate.header = TRUE, italics = seq(tab), 
                      title = title)",
    "```"
  )))
}
```

# Plots

## One plot per University, by category

```{r}
#| output: asis

for (i in 1:length(plot_list)){
  plot <- plot_list[[i]]
  
  university <- names(plot_list)[[i]]
  
  title <- paste0("Total interactions for\n", university, "\nposts, by category")
  
  plot_titled <- plot + 
    scale_x_discrete(labels = scales::label_wrap(15)) +
    ggplot2::labs(title = stringr::str_wrap(title, width = 35), x = "")
  
    res <- knitr::knit_child(quiet = TRUE, text = c(
    "```{r}",
    "#| echo: false",
    "print(plot_titled)",
    "```"
  ), envir = environment())
    
    cat(res, sep = '\n')
}
```